# Generated by Django 3.0.8 on 2020-07-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_bannedword_memberlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannedword',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterModelOptions(
            name='botaccessinfo',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='memberlist',
            options={'ordering': ['user_name']},
        ),
        migrations.AddField(
            model_name='bannedword',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
