# Generated by Django 3.0.8 on 2020-07-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20200710_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberlist',
            name='group',
        ),
        migrations.AddField(
            model_name='memberlist',
            name='group',
            field=models.ManyToManyField(blank=True, to='bot.BotAccessInfo'),
        ),
    ]
