# Generated by Django 3.0.8 on 2020-07-15 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20200710_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=300)),
                ('user_id', models.CharField(max_length=20)),
                ('group_name', models.CharField(max_length=300)),
                ('message_id', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('chat_id', models.CharField(max_length=20)),
                ('chat_type', models.TextField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'BotMessages',
                'ordering': ['-date'],
            },
        ),
    ]
